Add initial explanation for crypto used by AMS
canonical/anbox-cloud-docs pull request #114
Opened 2024-08-15 19:59 UTC by morphis

2024-08-15 20:00 UTC, morphis commented
@keirthana I've added this as a draft here for now as we need to discuss where to put this best. This form satisfies SEC0030 and will need to be repeated for all other services / components.

2024-08-19 08:46 UTC, keirthana commented
> @keirthana I've added this as a draft here for now as we need to discuss where to put this best. This form satisfies SEC0030 and will need to be repeated for all other services / components.

@morphis Yes, there should be a separate section for cryptography. Let me set that up through another PR. Before that, this is targeted for 1.24 right? In that case, I will set up a branch for 1.24 on the repo - I know we still have versioning to be spec'ed out but we might need something in place for current work.

2024-08-19 08:51 UTC, morphis commented
> > @keirthana I've added this as a draft here for now as we need to discuss where to put this best. This form satisfies SEC0030 and will need to be repeated for all other services / components.
> 
> @morphis Yes, there should be a separate section for cryptography. Let me set that up through another PR. Before that, this is targeted for 1.24 right? In that case, I will set up a branch for 1.24 on the repo - I know we still have versioning to be spec'ed out but we might need something in place for current work.

This is fine to go in any time, not tied to a release

2024-08-19 17:06 UTC, keirthana commented on explanation/security/crypto_ams.md
> +AMS is using cryptographic technology for
```suggestion
Anbox Management Service (AMS) is using cryptographic technology for:
```

2024-08-19 17:12 UTC, keirthana requested changes
Some minor changes, otherwise looks good!

2024-08-19 17:12 UTC, keirthana commented on explanation/security/crypto_ams.md
> +# AMS
```suggestion
# Cryptographic information: AMS 
```

2024-08-19 17:12 UTC, keirthana commented on explanation/security/crypto_ams.md
> +AMS authenticates with all of its clients through the use of mutual TLS. The server authenticates a client by the presented client certificate and checks if it is recorded in its trust store. A clien
```suggestion
AMS authenticates with all of its clients through the use of mutual TLS. The server authenticates a client by the presented client certificate and checks if it is recorded in its trust store. A client checks the certificate provided by the server against a recorded one. Once both sides have checked and accepted the presented certificate a TLS connection is established for API access.
```

2024-08-19 17:12 UTC, keirthana commented on explanation/security/crypto_ams.md
> +AMS uses for its server an RSA key with a length of 4096 bits. The standard AMS client `amc` uses a RSA key with a length of 4096 bits. The key in both cases is generated by the use of the [`rsa.Gene
```suggestion
AMS uses an RSA key with a length of 4096 bits for its server. The standard AMS client `amc` uses a RSA key with a length of 4096 bits. The key in both cases is generated by the use of the [`rsa.GenerateKey`](https://pkg.go.dev/crypto/rsa#GenerateKey) method as provided by the Go standard library.
```

2024-08-19 17:12 UTC, keirthana commented on explanation/security/crypto_ams.md
> +Authenticated client scan add additional certificates to the trust store AMS manages. The trust stored keeps a copy of all registered certificates and stores them in an [etcd database](https://etcd.i
```suggestion
Authenticated clients can add additional certificates to the trust store AMS manages. The trust stored keeps a copy of all registered certificates and stores them in an [etcd database](https://etcd.io/).
```

2024-08-19 17:12 UTC, keirthana commented on explanation/security/crypto_ams.md
> +Individual Anbox instances have access to a limited set of API endpoints exposed by the AMS server to submit status information at runtime. Access is authenticated by a scope limited JWT based token.
```suggestion
Individual Anbox instances have access to a limited set of API endpoints exposed by the AMS server to submit status information during runtime. Access is authenticated by a scope-limited JWT based token. The token is valid for one year and is signed with a [HMAC](https://www.okta.com/identity-101/hmac/) using SHA-256 (HS256) and a 64 byte secret key. The [`jwt.New`](https://pkg.go.dev/github.com/golang-jwt/jwt/v5#Token) method is used internally to generate the JWT token.
```

2024-08-19 17:13 UTC, keirthana commented
> > > @keirthana I've added this as a draft here for now as we need to discuss where to put this best. This form satisfies SEC0030 and will need to be repeated for all other services / components.
> > 
> > 
> > @morphis Yes, there should be a separate section for cryptography. Let me set that up through another PR. Before that, this is targeted for 1.24 right? In that case, I will set up a branch for 1.24 on the repo - I know we still have versioning to be spec'ed out but we might need something in place for current work.
> 
> This is fine to go in any time, not tied to a release

@morphis I had a closer look at this and I see that you have created the structure in place with the security folder. So let's go ahead with this and move things around when more information is available. Left a few suggestions to improve readability, otherwise LGTM.

2024-08-20 15:13 UTC, keirthana approved these changes
LGTM

2024-08-23 14:42 UTC, ajanon approved these changes
LGTM

2024-08-27 05:14 UTC, merged