feat: explain how to use the github action
canonical/anbox-cloud-docs pull request #119
Opened 2024-08-21 21:11 UTC by morphis

The Github action provides an easy path to enable the use of the Anbox Cloud Appliance on a Github runner as part of a workflow. This provides an initial howto to explain how to make use of the action.

2024-08-22 05:00 UTC, keirthana requested changes

2024-08-22 05:00 UTC, keirthana commented on howto/install-appliance/install-on-github.md
> +Alternatively you can also integrate the execution of actual integration tests in the test step. As the Android instance is connected over ADB, you can perform any operation as with any other connect
```suggestion
Alternatively, you can also integrate the execution of actual integration tests in the test step. As the Android instance is connected over ADB, you can perform any operation as with any other connected Android device.
```

2024-08-22 15:27 UTC, keirthana approved these changes

2024-08-23 14:39 UTC, ajanon approved these changes
LGTM

2024-08-27 05:13 UTC, merged