Improve contributing guide #131
canonical/anbox-cloud-docs pull request #151
Opened 2024-09-24 14:06 UTC by PitifulPete

Rename TOC heading to contribute. Add prerequisite for contributing to docs. Include quality checks by listing GitHub actions.

2024-09-25 10:23 UTC, keirthana requested changes
Thank you so much for trying to make the contributing guide better @PitifulPete! I have made some minor suggestions.

Also, let me know if you have signed the CLA (currently, the CLA check fails, but it does not pick up recent signups immediately)

2024-09-25 10:23 UTC, keirthana commented on contribute/landing.md
> +- Link check.
```suggestion
- Link check
```

2024-09-25 10:23 UTC, keirthana commented on contribute/landing.md
> +Contributing to our documentation is straightforward. We only require that all contributors sign the [Canonical contributor license agreement](https://ubuntu.com/legal/contributors), have a GitHub ac
```suggestion
Contributing to our documentation is straightforward. We only require that all contributors sign the [Canonical contributor license agreement](https://ubuntu.com/legal/contributors).

In order to contribute, you will need a [GitHub](https://github.com/) account, and set up a [git environment](https://github.com/canonical/open-documentation-academy/blob/main/getting-started/install_git.md). The [Get Started guide](https://github.com/canonical/open-documentation-academy/blob/main/getting-started/get_started.md#getting-your-environment-set-up) from the Canonical Open Documentation Academy is a useful resource.
```

2024-09-25 12:55 UTC, PitifulPete commented
> Thank you so much for trying to make the contributing guide better @PitifulPete! I have made some minor suggestions.
> 
> Also, let me know if you have signed the CLA (currently, the CLA check fails, but it does not pick up recent signups immediately)

I have signed the CLA

2024-09-26 07:29 UTC, keirthana commented
> > Thank you so much for trying to make the contributing guide better @PitifulPete! I have made some minor suggestions.
> > Also, let me know if you have signed the CLA (currently, the CLA check fails, but it does not pick up recent signups immediately)
> 
> I have signed the CLA

@PitifulPete It looks like the email you have used for this contribution does not match with the email with your Launchpad account? Could you check? That could be the reason why the CLA check is failing.

2024-09-26 09:15 UTC, PitifulPete commented
Hi @keirthana, you were right about the email discrepancy. I have fixed it by amending the last commit with a consistent email address but the CLA check still failed with a new error stating that I haven't signed it at all even though I have

2024-09-27 07:09 UTC, keirthana commented
> Hi @keirthana, you were right about the email discrepancy. I have fixed it by amending the last commit with a consistent email address but the CLA check still failed with a new error stating that I haven't signed it at all even though I have

@PitifulPete Unfortunately, your commit messages still have the email that is not connected to the LP account. Looking at the errors, it feels like the email with which you signed the CLA is not the email that is part of all your commits.

2024-09-27 08:53 UTC, PitifulPete commented
Solved. You can merge now @keirthana

2024-09-27 09:51 UTC, keirthana approved these changes

2024-09-27 09:51 UTC, merged