Create 1.23.2 release notes
canonical/anbox-cloud-docs pull request #189
Opened 2024-10-10 09:39 UTC by keirthana

Pending task:

- [x] Update image versions once candidate is ready
- [x] Update bundles once candidate is promoted is stable
- [x] Add bug fix when https://bugs.launchpad.net/anbox-cloud/+bug/2071806 is complete

2024-10-15 06:59 UTC, morphis requested changes

2024-10-15 06:59 UTC, morphis commented on reference/release-notes/1.23.2.md
> +| [CVE-2024-47068](https://nvd.nist.gov/vuln/detail/CVE-2024-47068) | Anbox Cloud web dashboard |
```suggestion
| [CVE-2024-47068](https://nvd.nist.gov/vuln/detail/CVE-2024-47068) | Anbox Cloud Dashboard, Anbox Cloud Appliance |
```

2024-10-15 06:59 UTC, morphis commented on reference/release-notes/1.23.2.md
> +| [CVE-2024-40677](https://source.android.com/docs/security/bulletin/2024-10-01#System) | Android 12, 13, 14, 15 |
```suggestion
| [CVE-2024-40677](https://source.android.com/docs/security/bulletin/2024-10-01#System) | Android 12, 13, 14 |
```

2024-10-15 06:59 UTC, morphis commented on reference/release-notes/1.23.2.md
> +| [CVE-2024-40676](https://source.android.com/docs/security/bulletin/2024-10-01#Framework) | Android 12, 13, 14, 15 |
```suggestion
| [CVE-2024-40676](https://source.android.com/docs/security/bulletin/2024-10-01#Framework) | Android 12, 13, 14 |
```

2024-10-16 06:29 UTC, ajanon approved these changes
LGTM

2024-10-16 06:33 UTC, adglkh approved these changes
LGTM

2024-10-16 06:35 UTC, morphis approved these changes

2024-10-16 07:26 UTC, merged