Improve guide for TLS configuration of the appliance
canonical/anbox-cloud-docs pull request #219
Opened 2024-11-14 19:50 UTC by morphis

I took a test run on the current how-to and had to adjust a few things to make it work after recent changes we did to the appliance.  We miss one bug fix for AMS to make it fully work which will come with 1.24.1 but will be soon in 1.24/beta. Regardless of this we should update the documentation to reflect how TLS should be setup.

2024-11-18 02:31 UTC, adglkh approved these changes
I agree that the section on using AWS Certificate Manager doesn't contain any Anbox Cloud specific content. However, it still provides value for people who want to use AWS Certificate Manager to create certificates and set things up for an appliance running on an EC2 instance (particularly for the `allows only HTTPS traffic` setting and the default outbound rule that allows all traffic).

Otherwise LGTM

2024-11-18 06:24 UTC, keirthana requested changes
Some minor suggestions

2024-11-18 06:24 UTC, keirthana commented on howto/anbox/tls-for-appliance.md
> +Configure the location for the appliance using the created DNS name by running the following command
```suggestion
Configure the location for the appliance using the created DNS name by running the following command:
```

2024-11-18 06:24 UTC, keirthana commented on howto/anbox/tls-for-appliance.md
> +The change will be automatically applied and causes all services components of the appliance to restart. If you want to defer the restart to a later point, you can use the `--no-restart` option.
```suggestion
The change will be automatically applied and will cause all services components of the appliance to restart. If you want to defer the restart to a later point, you can use the `--no-restart` option.
```

2024-11-18 06:24 UTC, keirthana commented on howto/anbox/tls-for-appliance.md
> +The `certbot` snap packages installed on your machine already set up a systemd timer that will automatically renew your certificates before they expire. However, in order to get the certificate renew
Did you mean a post-start hook?

```suggestion
The `certbot` snap packages installed on your machine would have already set up a systemd timer that automatically renews your certificates before they expire. However, to get the certificate renewed successfully for the appliance, you can create `post-start` hook for `certbot` which will automatically reconfigure it:
```

2024-11-18 06:24 UTC, keirthana commented on howto/anbox/tls-for-appliance.md
> +The appliance will be restarted at the end of the renewal of the SSL certificate to let the reverse proxy reload the certificate.
```suggestion
The appliance will be restarted when the renewal of the SSL certificate is complete, to let the reverse proxy reload the certificate.
```

2024-11-20 02:27 UTC, adglkh commented
> > I agree that the section on using AWS Certificate Manager doesn't contain any Anbox Cloud specific content. However, it still provides value for people who want to use AWS Certificate Manager to create certificates and set things up for an appliance running on an EC2 instance (particularly for the `allows only HTTPS traffic` setting and the default outbound rule that allows all traffic).
> 
> It may but the bigger problem is that it's hard for us to verify it doesn't break and still works. We seem to suffer a bit from content at the moment which is untested and turns out to be actually not helpful. Thus we need to be careful IMHO with what content we provide and we can actually keep working. The AWS UI has for example recently changed and I don't know if it is much longer the same way of enabling the TLS setup the document was describing. Especially as this is an edge case of non-Anbox Cloud functionality we should not keep it but much rather refer to external documentation (e.g. AWS) if needed. Wdyt?

A: Okay, let's drop the `using AWS Certificate Manager` section now and revisit it if necessary.

2024-11-20 12:39 UTC, ajanon approved these changes
LGTM

2024-11-20 13:06 UTC, keirthana approved these changes

2024-11-21 05:19 UTC, merged