First draft of 1.24.1 documentation
canonical/anbox-cloud-docs pull request #239
Opened 2024-12-06 06:34 UTC by keirthana

This PR contains updates for 1.24.1 release documentation.

Pending items that will be added in the course of review:

- [ ] Component versions will be added after Candidate is ready
- [ ] https://bugs.launchpad.net/anbox-cloud/+bug/2085098 requires confirmation from @morphis 
- [ ] https://bugs.launchpad.net/anbox-cloud/+bug/2071806 requires confirmation from @morphis 
- [ ] https://warthogs.atlassian.net/browse/AC-2847 requires confirmation from @ajanon 
- [ ] CVE details, if any

2024-12-10 08:18 UTC, ajanon requested changes
Two nitpicks

2024-12-10 08:18 UTC, ajanon commented on reference/release-notes/1.24.1.md
> +* Rendering does not work for AMD and Intel GPUs.For deployments that use AMD GPUs, the instance does not start and for deployments using Intel GPUs, the graphical output is incorrect.<!--AC-2963-->
Nitpick:
```suggestion
* Rendering does not work for AMD and Intel GPUs. For deployments that use AMD GPUs, the instance does not start and for deployments using Intel GPUs, the graphical output is incorrect.<!--AC-2963-->
```

2024-12-10 08:18 UTC, ajanon commented on reference/release-notes/1.24.1.md
> +The Anbox Cloud 1.23.2 release includes fixes from the respective upstreams for the following CVEs:
```suggestion
The Anbox Cloud 1.24.1 release includes fixes from the respective upstreams for the following CVEs:
```

2024-12-10 12:05 UTC, keirthana commented on reference/release-notes/1.24.1.md
> +| [CVE-2024-27397](https://ubuntu.com/security/CVE-2024-27397) | Linux kernel Ubuntu 22.04 |
Should we list our AOSP and AAOS images as the affected components since they are Ubuntu images and that is how the CVE affects us?
Like in [1.23.1 release notes](https://documentation.ubuntu.com/anbox-cloud/en/latest/reference/release-notes/1.23.1/#cves)?

2024-12-10 17:32 UTC, ajanon approved these changes
LGTM

2024-12-11 09:48 UTC, jat-canonical approved these changes
LGTM. THanks

2024-12-11 09:59 UTC, merged