docs(aar): add instructions to use instance profiles with AAR
canonical/anbox-cloud-docs pull request #37
Opened 2024-02-15 07:12 UTC by jat-canonical

This commit adds the instructions to make use of the newly added support for instance profiles in AAR.

2024-02-15 07:35 UTC, morphis requested changes
LGTM, can you though add a link to the release notes for 1.21 so we can get that linked for people interested?

2024-02-15 08:12 UTC, keirthana requested changes
Some minor suggestions and I see that Simon has already suggested adding the link to RN

2024-02-15 08:12 UTC, keirthana commented on howto/aar/deploy.md
> +There are two ways to configure the bucket access for AAR using the policy create above:
```suggestion
There are two ways to configure the bucket access for AAR using the policy create earlier:
```

2024-02-15 08:12 UTC, keirthana commented on howto/aar/deploy.md
> +1. Create an IAM user and an access key for this user, which the AAR will use. See the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for more d
```suggestion
1. Create an IAM user and an access key for this user, which the AAR will use. See the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) for more details on this. Assign the policy created earlier to this user.
```

2024-02-15 08:12 UTC, keirthana commented on howto/aar/deploy.md
> +2. Create an instance profile using the IAM policy created above and attach the instance profile to the instance where AAR is deployed. See the [AWS documentation](https://docs.aws.amazon.com/IAM/lat
```suggestion
2. Create an instance profile using the IAM policy created earlier and attach the instance profile to the instance where AAR is deployed. For more information, see the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html).
```

2024-02-15 10:38 UTC, keirthana approved these changes
LGTM

2024-02-15 11:26 UTC, keirthana commented
@morphis Are you fine with the current changes? Can I go ahead and merge+publish this update?

2024-02-15 11:35 UTC, morphis commented
@keirthana if we get a link into 1.21 release notes, then I am fine. However that seems to be still missing from the PR.

2024-02-15 11:49 UTC, jat-canonical commented
@morphis They have been added [here](https://github.com/canonical/anbox-cloud-docs/pull/37/files#diff-230f1d2db05c9124e7bbde9fb309b9033633b2c43d87c6e33610ee7b6cb5b4c8R61). Let me know if it needs changes.

2024-02-15 12:56 UTC, keirthana commented
@morphis I think there is some confusion here about whether you want the link from the doc to the RN or the reverse. In your most latest comment, you say "into the RN" , so I think it is the way we usually do - from the RN to the docs. Correct?

2024-02-20 10:30 UTC, jat-canonical commented
@morphis  could you confirm ?

2024-02-20 13:52 UTC, morphis commented
> @morphis I think there is some confusion here about whether you want the link from the doc to the RN or the reverse. In your most latest comment, you say "into the RN" , so I think it is the way we usually do - from the RN to the docs. Correct?

We need to link from the RN to the docs.

2024-02-21 07:12 UTC, keirthana commented
Since the pending comment has been addressed, I am merging and publishing this PR.

2024-02-21 07:13 UTC, merged