Update howto for streaming applications
canonical/anbox-cloud-docs pull request #64
Opened 2024-04-24 05:57 UTC by keirthana

In addition to [PR 51](https://github.com/canonical/anbox-cloud-docs/pull/51/), the howto guide for streaming applications also needs a update to mention the `--enable-streaming` option available from 1.22.

2024-04-24 07:08 UTC, ajanon approved these changes
LGTM

2024-04-24 10:34 UTC, adglkh requested changes

2024-04-25 05:13 UTC, keirthana commented on howto/application/stream.md
> +You can stream applications using the `amc` CLI or a stream client. The stream client can be the Anbox Cloud dashboard or your custom stream client.
I have tried a different approach which clarifies this and also keeps the focus on streaming. Please check if the current update is better.

2024-04-29 06:10 UTC, jat-canonical approved these changes
LGTM

2024-05-15 09:50 UTC, merged