feat(howto): create a new secion to introduce client-side video upsca…
canonical/anbox-cloud-docs pull request #99
Opened 2024-07-19 11:03 UTC by adglkh

…ling

2024-07-19 11:47 UTC, jat-canonical approved these changes
LGTM

2024-07-19 12:53 UTC, ajanon requested changes
One typo

2024-07-22 07:14 UTC, ajanon approved these changes
LGTM

2024-07-22 07:43 UTC, keirthana requested changes

2024-07-23 02:39 UTC, adglkh commented on howto/stream/enable-client-side-video-upscaling.md
> +To enable client-side video upscaling, initiating the `AnboxStream` object as follows:
Will fix

2024-07-23 02:44 UTC, adglkh commented
> Few minor corrections and one question:
> 
> For each of the actions, I feel like it would be more helpful if we mention _where_ to do the actions - for example, where would the user provide ``experimental.upscaling.useTargetFrameRate` option?


A: That may replicate what I put in the section `## How to enable client-side video upscaling` if we mention the usage for each option in action 
```html
<!DOCTYPE html>
    stream = new AnboxStream({
        targetElement: "anbox-stream",
        experimental: {
            upscaling: {
              enabled: true,
            },
        },
        ...
    });
```
However I don't have a strong opinion on this. I think that's better for a develop to get on this. I am fine with this too :)

2024-07-23 05:34 UTC, keirthana commented
> > Few minor corrections and one question:
> > For each of the actions, I feel like it would be more helpful if we mention _where_ to do the actions - for example, where would the user provide ``experimental.upscaling.useTargetFrameRate` option?
> 
> A: That may replicate what I put in the section `## How to enable client-side video upscaling` if we mention the usage for each option in action

In that case, I have suggested some rearrangement in the form of heading levels which would make the flow a bit easier. Let me know if that is fine with you. 

> 
> ```
> <!DOCTYPE html>
>     stream = new AnboxStream({
>         targetElement: "anbox-stream",
>         experimental: {
>             upscaling: {
>               enabled: true,
>             },
>         },
>         ...
>     });
> ```
> 
> However I don't have a strong opinion on this. I think that's better for a develop to get on this. I am fine with this too :)

2024-07-23 05:35 UTC, keirthana requested changes

2024-07-23 05:35 UTC, keirthana commented on howto/stream/enable-client-side-video-upscaling.md
> +# Client side video upscaling
```suggestion
# How to enable clien-side video upscaling
```

2024-07-23 05:35 UTC, keirthana commented on howto/stream/enable-client-side-video-upscaling.md
> +## How to enable client-side video upscaling
```suggestion
## Initiate the `AnboxStream` object
```

2024-07-23 05:35 UTC, keirthana commented on howto/stream/enable-client-side-video-upscaling.md
> +## Use target frame rate
```suggestion
### Use target frame rate
```

2024-07-23 05:35 UTC, keirthana commented on howto/stream/enable-client-side-video-upscaling.md
> +## Use custom fragment shader
```suggestion
### Use custom fragment shader
```

2024-07-29 09:18 UTC, adglkh commented
> > > Few minor corrections and one question:
> > > For each of the actions, I feel like it would be more helpful if we mention _where_ to do the actions - for example, where would the user provide ``experimental.upscaling.useTargetFrameRate` option?
> > 
> > 
> > A: That may replicate what I put in the section `## How to enable client-side video upscaling` if we mention the usage for each option in action
> 
> In that case, I have suggested some rearrangement in the form of heading levels which would make the flow a bit easier. Let me know if that is fine with you.
A: that looks good to me as well.
> 
> > ```
> > <!DOCTYPE html>
> >     stream = new AnboxStream({
> >         targetElement: "anbox-stream",
> >         experimental: {
> >             upscaling: {
> >               enabled: true,
> >             },
> >         },
> >         ...
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However I don't have a strong opinion on this. I think that's better for a develop to get on this. I am fine with this too :)

2024-07-29 09:23 UTC, keirthana commented on howto/stream/enable-client-side-video-upscaling.md
> +# How to enable clien-side video upscaling
```suggestion
# How to enable client-side video upscaling
```

2024-07-29 09:25 UTC, keirthana approved these changes
One minor type, otherwise all looks good, thanks!

2024-07-29 15:13 UTC, keirthana commented
@adglkh Added some words to ignore list for the spellcheck to pass, hope that is fine :crossed_fingers:

2024-07-30 02:16 UTC, adglkh commented
@keirthana 
There are a few links broken, and we should be good now.
@morphis 
Could you please take a look?

Thanks

2024-07-30 05:30 UTC, keirthana commented
> @keirthana There are a few links broken, and we should be good now. @morphis Could you please take a look?
> 

I added a [fix](https://github.com/canonical/anbox-cloud-docs/pull/103) for ignoring anchors (the link check was very flaky because of that), so should be good now.
> Thanks

2024-07-30 17:19 UTC, morphis approved these changes
LGTM

2024-07-31 12:57 UTC, merged